services:
  postgres:
    image: postgres:13.15-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_DB: seminar
      POSTGRES_USER: me
      POSTGRES_PASSWORD: superpw
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    command: -c config_file=/etc/postgresql.conf
    volumes:
      - ./pg.conf:/etc/postgresql.conf

networks:
  postgres-network:
    name: postgres-network